- hosts: docker
  become: true
  tasks:
  
  - name: Prune Unused Docker Images 
    community.docker.docker_prune:
      containers: false
      images: true
      images_filters:
        dangling: true
      networks: false
      volumes: false
      builder_cache: false
      
