- hosts: docker
  become: true
  tasks:

  - name: Install pip
      apt:
        update_cache: yes
        name:
          - python3-pip

  - name: Install pexpect
      pip:
        name: pexpect
        
  - name: Prune Unused Docker Images 
    ansible.builtin.expect:
      command: docker image prune
      responses:
        'Confirmation': 'y'
      
