---
- name: Update Windows, Arch Linux, and Debian
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Update Windows
      when: ansible_facts['os_family'] == 'Windows'
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      register: win_update_result

    - name: Check if Windows requires a reboot
      when: win_update_result.changed and win_update_result.reboot_required | default(false)
      ansible.windows.win_reboot:
        reboot_timeout: 600
      register: win_reboot_result

    - name: Update Arch Linux
      when: ansible_facts['os_family'] == 'Arch'
      community.general.pacman:
        update_cache: true
        upgrade: true
      register: arch_update_result

    - name: Check if Arch Linux requires a reboot
      when: ansible_facts['os_family'] == 'Arch' and arch_update_result.changed
      ansible.builtin.stat:
        path: /run/reboot-required
      register: arch_reboot_required

    - name: Reboot Arch Linux if required
      when: arch_reboot_required.stat.exists | default(false)
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Update Debian Linux
      when: ansible_facts['os_family'] == 'Debian'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist

    - name: Check if Arch Linux requires a reboot
      when: ansible_facts['os_family'] == 'Debian'
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_checksum=false

    - name: Reboot Debian Linux if required
      when: ansible_facts['os_family'] == 'Debian'
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
