- hosts: docker
  become: true
  tasks:

  - name: Installing pexpect
    ansible.builtin.apt:
      name: python3-pexpect
      update_cache: yes
        
  - name: Prune Unused Docker Images 
    ansible.builtin.expect:
      command: docker image prune
      responses:
        'WARNING! This will remove all dangling images.\r\nAre you sure you want to continue? [y/N] ': 
          - 'y'
      
